[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['cd BACKEND && npm install']

[phases.build]
cmds = ['cd BACKEND && npm run db:generate']

[start]
cmd = 'cd BACKEND && npm start'

