# 🔄 CI/CD PIPELINE - GitHub Actions

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Backend Tests
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Run Linter
        working-directory: ./backend
        run: npm run lint
      
      - name: Run Tests
        working-directory: ./backend
        run: npm test
      
      - name: Check Coverage
        working-directory: ./backend
        run: npm run test:coverage
        env:
          CI: true

  # Frontend Tests
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run Linter
        working-directory: ./frontend
        run: npm run lint
      
      - name: Run Tests
        working-directory: ./frontend
        run: npm test
      
      - name: Check Coverage
        working-directory: ./frontend
        run: npm run test:coverage
        env:
          CI: true

  # Build Check
  build-check:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Build Backend
        working-directory: ./backend
        run: npm run build
      
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  # E2E Tests
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [build-check]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Run E2E Tests
        run: npm run test:e2e
      
  # Deploy (Only on main branch)
  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Backend
        # Add your deployment commands here
        run: echo "Deploying backend..."
      
      - name: Deploy Frontend
        # Add your deployment commands here
        run: echo "Deploying frontend..."
      
      - name: Run Smoke Tests
        run: npm run test:smoke

