name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v0.2.9
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: backend
        detach: false

  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v0.2.9
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: frontend
        detach: false

